# ===================================================================
# Spring boot configuration for "local" profile.
#
# This configuration overrides the application.yml file
# ===================================================================

# logging properties

logging:
  level:
    ROOT: INFO
    com.hbo.smart: INFO

server:
  port: 9080

# hbo common framework properties

common:
  rest:
    client:
      apis:
        admin:
          base-url: http://croappsmartd:9090/
          health-url: http://croappsmartd:9090/api/admin/v1/health
          affiliate-subscriber:
            base-url: http://croappsmartd:9091/
            health-url: http://croappsmartd:9091/api/affiliate-subscriber/v1/health
          deal:
            base-url: http://croappsmartd:9092/
            health-url: http://croappsmartd:9092/api/deals-accrual/v1/health
          billing:
            base-url: http://croappsmartd:9095/
            health-url: http://croappsmartd:9095/api/billing-invoice-service/v1/health
          smart-webapp:
            base-url: http://croappsmartd:9080/
            health-url: http://croappsmartd:9080/health
  web:
    sso:
      sp:
        base-url: http://localhost:9080
        metadata.entity-id: urn:com.hbo:smart:smart-web-app-local
      idp.metadata.url: https://twdev.oktapreview.com/app/exkj9aiqrdxviEVFM0h7/sso/saml/metadata
      logout.url: https://hbobeta.oktapreview.com/login/signout
      default-success-target-url: /
      membership-roles:
        "*SMART Project Team":
          - ROLE_ADMIN
          - ROLE_USERS

# spring properties

spring:
  resources:
    cache-period: 31536000