# ===================================================================
# Spring boot configuration for "uat02b" profile.
#
# This configuration overrides the application.yml file
# ===================================================================

logging:
  level:
    ROOT: INFO
    com.hbo.smart: INFO

server:
  port: 8443
  ssl:
    enabled: true
    key-alias: smart-beta.homebox.com
    key-store: /hboprod/cro/ssl/commonrsa/smart.jks
    key-store-password: itiPVZ0FcX3L
    key-store-provider: SUN
    key-store-type: JKS

# hbo common framework properties

common:
  rest:
    client:
      security:
        oauth2:
          client-name: smart-web-app
          client-secret: BNdaiZ8Du6X
          access-token-uri: https://oauthbeta.homebox.com/auth/v1/tokens
      apis:
        admin:
          base-url: https://smart-adminbeta-api.homebox.com/
          health-url: https://uxsmartapp02b.homebox.com:8444/api/admin/v1/health
        affiliate-subscriber:
          base-url: https://smart-affiliate-subscriberbeta-api.homebox.com/
          health-url: https://uxsmartapp02b.homebox.com:8445/api/affiliate-subscriber/v1/health
        deal:
          base-url: https://smart-dealsbeta-api.homebox.com/
          health-url: https://uxsmartapp02b.homebox.com:8446/api/deals-accrual/v1/health
        billing:
          base-url: https://smart-billingbeta-api.homebox.com/
          health-url: https://uxsmartapp02b.homebox.com:8447/health
        smart-webapp:
          base-url: https://smart-beta.homebox.com/
          health-url: https://uxsmartapp02b.homebox.com:8443/health
  web:
    sso:
      sp:
        base-url: https://smart-beta.homebox.com
        metadata.entity-id: com.hbo:smart:beta#6FD86
      idp.metadata.url: https://tw.oktapreview.com/app/exkjmvqorqrLitvrS0h7/sso/saml/metadata
      logout.url: https://sso.homeboxoffice.com/sso/logout
      default-success-target-url: /
      membership-roles:
        "*SMART Project Team":
          - ROLE_ADMIN
          - ROLE_USERS

# spring properties

spring:
  resources:
    cache-period: 31536000
