# ===================================================================
# Spring Boot configuration
#
# This configuration will be overridden by the Spring profile you use
# ===================================================================

# logging properties

logging:
  level:
    ROOT: INFO
    com.hbo.smart: INFO

# embedded server properties

server:
  port: 9080
  context-path: /
  session:
    timeout: 7200 # Session timeout in seconds, aka 120 mins

# hbo common framework properties

common:
  rest:
    client:
      security:
        oauth2:
          client-name: smart-web-app
          client-secret: nEvZJFyunav
          access-token-uri: https://oauthdev.homebox.com/auth/v1/tokens

# security properties

security:
  basic:
    enabled: false
  enable-csrf: false

# hbo common framework properties


# spring properties

spring:
  http:
    encoding:
      force: true
  profiles:
    active: local




